// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

import '@base44/sdk';

export type Oficina = string;
export type Cliente = string;
export type ClienteSnapshot = string;
export type Veiculo = string;
export type PlacaSnapshot = string;
export type VeiculoSnapshot = string;
export type DataPrevista = string;
export type Horario = string;
export type Tipo = "avaliacao" | "orcamento" | "manutencao" | "revisao" | "retorno" | "servico_agendado" | "outro";
export type Motivo = string;
export type Observacao = string;
export type Status =
  | "agendado"
  | "confirmado"
  | "veiculo_recebido"
  | "em_atendimento"
  | "concluido"
  | "cancelado"
  | "nao_compareceu";
export type OrcamentoRelacionado = string;
export type OSRelacionada = string;
export type ChegadaReal = string;

export interface Appointment {
  workshop_id: Oficina;
  customer_id: Cliente;
  customer_name_snapshot?: ClienteSnapshot;
  vehicle_id: Veiculo;
  plate_snapshot?: PlacaSnapshot;
  vehicle_description_snapshot?: VeiculoSnapshot;
  scheduled_date: DataPrevista;
  scheduled_time?: Horario;
  type?: Tipo;
  reason?: Motivo;
  notes?: Observacao;
  status?: Status;
  quote_id?: OrcamentoRelacionado;
  work_order_id?: OSRelacionada;
  actual_arrival?: ChegadaReal;
}

export type Oficina = string;
export type Agendamento = string;
export type DataAnterior = string;
export type NovaData = string;
export type Quando = string;
export type Usuario = string;
export type Motivo = string;

export interface AppointmentHistory {
  workshop_id: Oficina;
  appointment_id: Agendamento;
  previous_date?: DataAnterior;
  new_date?: NovaData;
  changed_at?: Quando;
  changed_by?: Usuario;
  reason?: Motivo;
}

export type Oficina = string;
export type NomeRazaoSocial = string;
export type TipoDePessoa = "PF" | "PJ" | "EXTERIOR";
export type RazaoSocial = string;
export type NomeFantasia = string;
export type CPFCNPJ = string;
export type InscricaoEstadual = string;
export type InscricaoMunicipal = string;
export type Telefone = string;
export type WhatsApp = string;
export type EMail = string;
export type CEP = string;
export type Endereco = string;
export type Numero = string;
export type Complemento = string;
export type Bairro = string;
export type Cidade = string;
export type Estado = string;
export type CodigoIBGEDoMunicipio = string;
export type Pais = string;
export type CodigoDoPais = string;
export type ConsumidorFinal = boolean;
export type PessoaDoExterior = boolean;
export type Observacoes = string;
export type Ativo = boolean;

export interface Customer {
  workshop_id: Oficina;
  name: NomeRazaoSocial;
  person_type?: TipoDePessoa;
  razao_social?: RazaoSocial;
  fantasy_name?: NomeFantasia;
  cpf_cnpj?: CPFCNPJ;
  inscricao_estadual?: InscricaoEstadual;
  inscricao_municipal?: InscricaoMunicipal;
  phone?: Telefone;
  whatsapp?: WhatsApp;
  email?: EMail;
  cep?: CEP;
  address?: Endereco;
  number?: Numero;
  complement?: Complemento;
  neighborhood?: Bairro;
  city?: Cidade;
  state?: Estado;
  city_ibge_code?: CodigoIBGEDoMunicipio;
  country?: Pais;
  country_code?: CodigoDoPais;
  final_consumer?: ConsumidorFinal;
  foreign_indicator?: PessoaDoExterior;
  notes?: Observacoes;
  active?: Ativo;
}

export type Oficina = string;
export type URLDoEvolutionGO = string;
export type NomeDaInstancia = string;
export type ChaveDaAPI = string;
export type SufixoDaChave = string;

export interface EvolutionGoConfig {
  workshop_id: Oficina;
  base_url: URLDoEvolutionGO;
  instance_name: NomeDaInstancia;
  api_key: ChaveDaAPI;
  api_key_last4?: SufixoDaChave;
}

export type Oficina = string;
export type Descricao = string;
export type Categoria = string;
export type Fornecedor = string;
export type Beneficiario = string;
export type Valor = number;
export type Data = string;
export type Vencimento = string;
export type DataDePagamento = string;
export type Status = "pendente" | "pago" | "vencido" | "cancelado";
export type FormaDePagamento = "dinheiro" | "pix" | "cartao_debito" | "cartao_credito" | "outro";
export type Observacao = string;
export type Tipo = "fixa" | "eventual";
export type Recorrente = boolean;
export type Periodicidade = "mensal" | "semanal" | "anual";
export type DiaDeVencimento = number;
export type InicioDaRecorrencia = string;
export type FimDaRecorrencia = string;
export type DespesaRecorrenteOrigem = string;
export type PedidoDeCompraOrigem = string;
export type DocumentoFiscalDeOrigem = string;
export type Comprovante = string;
export type MesDeReferenciaYYYYMM = string;

export interface Expense {
  workshop_id: Oficina;
  description: Descricao;
  category?: Categoria;
  supplier_id?: Fornecedor;
  beneficiary?: Beneficiario;
  amount: Valor;
  date?: Data;
  due_date?: Vencimento;
  payment_date?: DataDePagamento;
  status?: Status;
  payment_method?: FormaDePagamento;
  notes?: Observacao;
  type?: Tipo;
  is_recurring?: Recorrente;
  recurrence_period?: Periodicidade;
  recurrence_day?: DiaDeVencimento;
  recurrence_start?: InicioDaRecorrencia;
  recurrence_end?: FimDaRecorrencia;
  parent_expense_id?: DespesaRecorrenteOrigem;
  purchase_order_id?: PedidoDeCompraOrigem;
  fiscal_document_id?: DocumentoFiscalDeOrigem;
  attachment_url?: Comprovante;
  month_key?: MesDeReferenciaYYYYMM;
}

export type Oficina = string;
export type Tipo = "entrada" | "saida";
export type Origem = "os" | "pedido" | "despesa" | "outro";
export type IDDeOrigem = string;
export type Descricao = string;
export type Data = string;
export type Valor = number;
export type FormaDePagamento = "dinheiro" | "pix" | "cartao_debito" | "cartao_credito" | "outro";
export type Status = "ativo" | "cancelado";
export type Cliente = string;
export type ClienteSnapshot = string;
export type Fornecedor = string;
export type FornecedorSnapshot = string;
export type CategoriaDespesas = string;

export interface FinancialTransaction {
  workshop_id: Oficina;
  type: Tipo;
  origin_type: Origem;
  origin_id?: IDDeOrigem;
  description?: Descricao;
  date?: Data;
  amount: Valor;
  payment_method?: FormaDePagamento;
  status?: Status;
  customer_id?: Cliente;
  customer_name_snapshot?: ClienteSnapshot;
  supplier_id?: Fornecedor;
  supplier_name_snapshot?: FornecedorSnapshot;
  category?: CategoriaDespesas;
}

export type Oficina = string;
export type Provedor = string;
export type TipoDeCredencial = string;
export type ReferenciaSegura = string;
export type ValidadeDoCertificado = string;
export type Status = "nao_configurada" | "ativa" | "expirada" | "erro" | "revogada";
export type UltimaValidacao = string;

export interface FiscalCredential {
  workshop_id: Oficina;
  provider: Provedor;
  credential_type: TipoDeCredencial;
  credential_reference?: ReferenciaSegura;
  certificate_expiration?: ValidadeDoCertificado;
  status?: Status;
  last_validated_at?: UltimaValidacao;
}

export type Oficina = string;
export type Direcao = "INBOUND" | "OUTBOUND";
export type TipoDeDocumento = "NFE" | "NFSE";
export type TipoDeOrigem = "WORK_ORDER" | "MANUAL" | "XML";
export type IDDaOrigem = string;
export type Cliente = string;
export type Fornecedor = string;
export type Status =
  | "DRAFT"
  | "VALIDATION_ERROR"
  | "READY"
  | "REGISTERED"
  | "PARTIALLY_PROCESSED"
  | "PROCESSED"
  | "SENT"
  | "PROCESSING"
  | "AUTHORIZED"
  | "REJECTED"
  | "CANCELED"
  | "REPLACED"
  | "ERROR";
export type DataDeEmissao = string;
export type Competencia = string;
export type Provedor = string;
export type Ambiente = "homologacao" | "producao";
export type Numero = string;
export type Serie = string;
export type ChaveDeAcesso = string;
export type DataDeEntrada = string;
export type IDExterno = string;
export type CodigoDeVerificacao = string;
export type Protocolo = string;
export type TotalDeServicos = number;
export type TotalDeProdutos = number;
export type Desconto = number;
export type Deducoes = number;
export type TotalDoDocumento = number;
export type XML = string;
export type XMLPrivado = string;
export type XMLValidado = boolean;
export type EstoqueProcessadoEm = string;
export type BloqueioDeProcessamentoDoEstoque = string;
export type FinanceiroProcessadoEm = string;
export type BloqueioDeProcessamentoFinanceiro = string;
export type ContaAPagar = string;
export type PDF = string;
export type URLPublica = string;
export type UltimoCodigoDeErro = string;
export type UltimoErro = string;

export interface FiscalDocument {
  workshop_id: Oficina;
  direction: Direcao;
  document_type: TipoDeDocumento;
  source_type: TipoDeOrigem;
  source_id?: IDDaOrigem;
  customer_id?: Cliente;
  supplier_id?: Fornecedor;
  status: Status;
  issue_date?: DataDeEmissao;
  competence_date?: Competencia;
  provider?: Provedor;
  environment?: Ambiente;
  number?: Numero;
  series?: Serie;
  access_key?: ChaveDeAcesso;
  entry_date?: DataDeEntrada;
  external_id?: IDExterno;
  verification_code?: CodigoDeVerificacao;
  protocol?: Protocolo;
  total_services?: TotalDeServicos;
  total_products?: TotalDeProdutos;
  discount?: Desconto;
  deductions?: Deducoes;
  taxes?: TotaisDeTributos;
  total_document?: TotalDoDocumento;
  issuer_snapshot?: SnapshotDoPrestador;
  customer_snapshot?: SnapshotDoTomador;
  supplier_snapshot?: SnapshotDoFornecedor;
  fiscal_setting_snapshot?: SnapshotDaConfiguracaoFiscal;
  xml_url?: XML;
  xml_file_uri?: XMLPrivado;
  xml_validated?: XMLValidado;
  stock_processed_at?: EstoqueProcessadoEm;
  stock_processing_token?: BloqueioDeProcessamentoDoEstoque;
  financial_processed_at?: FinanceiroProcessadoEm;
  financial_processing_token?: BloqueioDeProcessamentoFinanceiro;
  expense_id?: ContaAPagar;
  pdf_url?: PDF;
  public_url?: URLPublica;
  last_error_code?: UltimoCodigoDeErro;
  last_error_message?: UltimoErro;
}
export interface TotaisDeTributos {}
export interface SnapshotDoPrestador {}
export interface SnapshotDoTomador {}
export interface SnapshotDoFornecedor {}
export interface SnapshotDaConfiguracaoFiscal {}

export type Oficina = string;
export type DocumentoFiscal = string;
export type TipoDoEvento =
  | "CREATED"
  | "XML_IMPORTED"
  | "XML_LINKED"
  | "VALIDATION_ERROR"
  | "REGISTERED"
  | "STOCK_PROCESSED"
  | "FINANCIAL_CREATED"
  | "SENT"
  | "PROCESSING"
  | "AUTHORIZED"
  | "REJECTED"
  | "CANCELED"
  | "REPLACED"
  | "RETRY"
  | "QUERY"
  | "ERROR";
export type Status = string;
export type Provedor = string;
export type IDDaRequisicao = string;
export type Protocolo = string;
export type CodigoDoErro = string;
export type MensagemDoErro = string;
export type CriadoPor = string;

export interface FiscalDocumentEvent {
  workshop_id: Oficina;
  fiscal_document_id: DocumentoFiscal;
  event_type: TipoDoEvento;
  status?: Status;
  provider?: Provedor;
  request_id?: IDDaRequisicao;
  protocol?: Protocolo;
  error_code?: CodigoDoErro;
  error_message?: MensagemDoErro;
  created_by?: CriadoPor;
}

export type Oficina = string;
export type DocumentoFiscal = string;
export type TipoDoItemDeOrigem = "WORK_ORDER_ITEM" | "XML_ITEM" | "MANUAL_ITEM";
export type ItemDeOrigem = string;
export type TipoDoItem = "SERVICE" | "PRODUCT" | "OTHER";
export type MaterialRelacionado = string;
export type CodigoNoFornecedor = string;
export type GTINEAN = string;
export type Descricao = string;
export type Quantidade = number;
export type Unidade = string;
export type ValorUnitario = number;
export type Desconto = number;
export type Total = number;
export type ControlarEstoque = boolean;
export type EstoqueProcessado = boolean;

export interface FiscalDocumentItem {
  workshop_id: Oficina;
  fiscal_document_id: DocumentoFiscal;
  source_item_type?: TipoDoItemDeOrigem;
  source_item_id?: ItemDeOrigem;
  item_type: TipoDoItem;
  material_id?: MaterialRelacionado;
  supplier_product_code?: CodigoNoFornecedor;
  gtin?: GTINEAN;
  description: Descricao;
  quantity?: Quantidade;
  unit?: Unidade;
  unit_price?: ValorUnitario;
  discount?: Desconto;
  total?: Total;
  track_stock?: ControlarEstoque;
  stock_processed?: EstoqueProcessado;
  service_fiscal_snapshot?: SnapshotFiscalDoServico;
  product_fiscal_snapshot?: SnapshotFiscalDoProduto;
  tax_snapshot?: SnapshotDeTributos;
}
export interface SnapshotFiscalDoServico {}
export interface SnapshotFiscalDoProduto {}
export interface SnapshotDeTributos {}

export type Oficina = string;
export type TipoDaOrigem = "FISCAL_DOCUMENT" | "PURCHASE_ORDER";
export type IDDaOrigem = string;
export type Operacao = "STOCK" | "FINANCIAL" | "RECEIPT";
export type Token = string;
export type Status = "ACTIVE" | "RELEASED";
export type ExpiraEm = string;

export interface FiscalOperationLock {
  workshop_id: Oficina;
  source_type: TipoDaOrigem;
  source_id: IDDaOrigem;
  operation: Operacao;
  token: Token;
  status: Status;
  expires_at: ExpiraEm;
}

export type Oficina = string;
export type RegimeTributario = "MEI" | "SIMPLES_NACIONAL" | "LUCRO_PRESUMIDO" | "LUCRO_REAL" | "OUTRO";
export type OptantePeloSimplesNacional = boolean;
export type MEI = boolean;
export type InscricaoMunicipal = string;
export type InscricaoEstadual = string;
export type CodigoIBGEDoMunicipio = string;
export type Municipio = string;
export type UF = string;
export type Ambiente = "homologacao" | "producao";
export type Provedor = string;
export type ModoDeEmissao = "manual" | "automatica_finalizacao";
export type SerieDaNFSERPS = string;
export type ProximoNumeroDeRPS = number;
export type StatusDaConexao = "NOT_TESTED" | "CONNECTED" | "ERROR";
export type ConexaoTestadaEm = string;
export type StatusDaHomologacao = "NOT_STARTED" | "PENDING" | "APPROVED" | "REJECTED";
export type HomologacaoAprovadaEm = string;
export type CodigoDeServicoPadrao = string;
export type ItemDaListaPadrao = string;
export type NBSPadrao = string;
export type AliquotaISSPadrao = number;
export type ISSRetidoPorPadrao = boolean;
export type NaturezaDaOperacaoPadrao = string;
export type ExigibilidadePadrao = string;
export type NomeDoContador = string;
export type EscritorioContabil = string;
export type TelefoneDoContador = string;
export type EMailDoContador = string;

export interface FiscalSetting {
  workshop_id: Oficina;
  regime_tributario?: RegimeTributario;
  simples_nacional?: OptantePeloSimplesNacional;
  mei?: MEI;
  inscricao_municipal?: InscricaoMunicipal;
  inscricao_estadual?: InscricaoEstadual;
  municipio_codigo_ibge?: CodigoIBGEDoMunicipio;
  municipio_nome?: Municipio;
  uf?: UF;
  ambiente_fiscal?: Ambiente;
  provedor_fiscal?: Provedor;
  modo_emissao?: ModoDeEmissao;
  nfse_serie?: SerieDaNFSERPS;
  nfse_proximo_rps?: ProximoNumeroDeRPS;
  connection_status?: StatusDaConexao;
  connection_tested_at?: ConexaoTestadaEm;
  homologation_status?: StatusDaHomologacao;
  homologation_approved_at?: HomologacaoAprovadaEm;
  codigo_servico_municipal_padrao?: CodigoDeServicoPadrao;
  item_lista_servico_padrao?: ItemDaListaPadrao;
  nbs_padrao?: NBSPadrao;
  aliquota_iss_padrao?: AliquotaISSPadrao;
  iss_retido_padrao?: ISSRetidoPorPadrao;
  natureza_operacao_padrao?: NaturezaDaOperacaoPadrao;
  exigibilidade_padrao?: ExigibilidadePadrao;
  contador_nome?: NomeDoContador;
  contador_escritorio?: EscritorioContabil;
  contador_telefone?: TelefoneDoContador;
  contador_email?: EMailDoContador;
}

export type Oficina = string;
export type CodigoInterno = string;
export type CodigoDeBarras = string;
export type GTIN = string;
export type NomeComercial = string;
export type Descricao = string;
export type Categoria = string;
export type Marca = string;
export type Unidade = string;
export type Custo = number;
export type PrecoDeVenda = number;
export type Estoque = number;
export type EstoqueMinimo = number;
export type FornecedorPreferencial = string;
export type Observacao = string;
export type Ativo = boolean;

export interface Material {
  workshop_id: Oficina;
  code?: CodigoInterno;
  barcode?: CodigoDeBarras;
  gtin?: GTIN;
  name?: NomeComercial;
  description: Descricao;
  category?: Categoria;
  brand?: Marca;
  unit?: Unidade;
  cost?: Custo;
  sale_price?: PrecoDeVenda;
  stock?: Estoque;
  minimum_stock?: EstoqueMinimo;
  preferred_supplier_id?: FornecedorPreferencial;
  notes?: Observacao;
  active?: Ativo;
}

export type Oficina = string;
export type Nome = string;

export interface MaterialCategory {
  workshop_id: Oficina;
  name: Nome;
}

export type Oficina = string;
export type Material = string;
export type NCM = string;
export type CEST = string;
export type OrigemDaMercadoria = string;
export type ObservacaoFiscal = string;
export type Ativo = boolean;

export interface MaterialFiscalProfile {
  workshop_id: Oficina;
  material_id: Material;
  ncm?: NCM;
  cest?: CEST;
  origem_mercadoria?: OrigemDaMercadoria;
  observacao_fiscal?: ObservacaoFiscal;
  active?: Ativo;
}

export type Oficina = string;
export type OrdemDeServico = string;
export type Cliente = string;
export type ClienteSnapshot = string;
export type Valor = number;
export type FormaDePagamento = "dinheiro" | "pix" | "cartao_debito" | "cartao_credito" | "outro";
export type DataDoPagamento = string;
export type Observacao = string;
export type UsuarioQueRegistrou = string;
export type Status = "ativo" | "cancelado";
export type MotivoDoCancelamento = string;
export type CanceladoEm = string;
export type CanceladoPor = string;

export interface Payment {
  workshop_id: Oficina;
  work_order_id: OrdemDeServico;
  customer_id?: Cliente;
  customer_name_snapshot?: ClienteSnapshot;
  amount: Valor;
  method?: FormaDePagamento;
  date?: DataDoPagamento;
  notes?: Observacao;
  registered_by?: UsuarioQueRegistrou;
  status?: Status;
  cancel_reason?: MotivoDoCancelamento;
  cancelled_at?: CanceladoEm;
  cancelled_by?: CanceladoPor;
}

export type Oficina = string;
export type Numero = string;
export type Data = string;
export type Fornecedor = string;
export type FornecedorSnapshot = string;
export type SolicitacaoDeOrigem = string;
export type PrevisaoDeEntrega = string;
export type Observacoes = string;
export type Responsavel = string;
export type Status = "rascunho" | "pedido_realizado" | "parcialmente_recebido" | "recebido" | "cancelado";
export type Subtotal = number;
export type Desconto = number;
export type Total = number;
export type StatusDePagamento = "nao_pago" | "parcialmente_pago" | "pago" | "cancelado";
export type ValorPago = number;
export type DataDeRecebimento = string;
export type ObservacoesDoRecebimento = string;
export type BloqueioDeProcessamentoDoRecebimento = string;

export interface PurchaseOrder {
  workshop_id: Oficina;
  number: Numero;
  date?: Data;
  supplier_id: Fornecedor;
  supplier_name_snapshot?: FornecedorSnapshot;
  request_id?: SolicitacaoDeOrigem;
  expected_delivery?: PrevisaoDeEntrega;
  notes?: Observacoes;
  responsible?: Responsavel;
  status?: Status;
  subtotal?: Subtotal;
  discount?: Desconto;
  total?: Total;
  payment_status?: StatusDePagamento;
  paid_amount?: ValorPago;
  received_date?: DataDeRecebimento;
  receipt_notes?: ObservacoesDoRecebimento;
  receipt_processing_token?: BloqueioDeProcessamentoDoRecebimento;
}

export type Oficina = string;
export type Pedido = string;
export type Material = string;
export type Descricao = string;
export type Quantidade = number;
export type Unidade = string;
export type ValorUnitario = number;
export type Total = number;
export type QtdRecebida = number;
export type Recebido = boolean;

export interface PurchaseOrderItem {
  workshop_id: Oficina;
  order_id: Pedido;
  material_id?: Material;
  description: Descricao;
  quantity?: Quantidade;
  unit?: Unidade;
  unit_price?: ValorUnitario;
  total?: Total;
  received_quantity?: QtdRecebida;
  received?: Recebido;
}

export type Oficina = string;
export type Numero = string;
export type Data = string;
export type Responsavel = string;
export type Observacao = string;
export type Status =
  | "rascunho"
  | "cotacao"
  | "aguardando_resposta"
  | "aprovado"
  | "pedido_realizado"
  | "parcialmente_recebido"
  | "recebido"
  | "cancelado";
export type FornecedoresSelecionados = string[];

export interface PurchaseRequest {
  workshop_id: Oficina;
  number: Numero;
  date?: Data;
  responsible?: Responsavel;
  notes?: Observacao;
  status?: Status;
  supplier_ids?: FornecedoresSelecionados;
}

export type Oficina = string;
export type Solicitacao = string;
export type Material = string;
export type Descricao = string;
export type Quantidade = number;
export type Unidade = string;
export type Observacao = string;
export type CotacoesDosFornecedores = {
  supplier_id?: string;
  supplier_name_snapshot?: string;
  unit_price?: number;
  notes?: string;
}[];
export type FornecedorSelecionado = string;
export type PrecoSelecionado = number;

export interface PurchaseRequestItem {
  workshop_id: Oficina;
  request_id: Solicitacao;
  material_id?: Material;
  description: Descricao;
  quantity?: Quantidade;
  unit?: Unidade;
  notes?: Observacao;
  supplier_quotes?: CotacoesDosFornecedores;
  selected_supplier_id?: FornecedorSelecionado;
  selected_unit_price?: PrecoSelecionado;
}

export type Oficina = string;
export type Numero = string;
export type Data = string;
export type Validade = string;
export type Cliente = string;
export type ClienteSnapshot = string;
export type Veiculo = string;
export type PlacaSnapshot = string;
export type VeiculoSnapshot = string;
export type Quilometragem = number;
export type RelatoDoCliente = string;
export type DiagnosticoObservacao = string;
export type ObservacoesAdicionais = string;
export type Previsao = string;
export type FotosAnexadas = string[];
export type Status = "rascunho" | "aguardando_aprovacao" | "aprovado" | "cancelado";
export type SubtotalPecas = number;
export type SubtotalMaoDeObra = number;
export type Socorro = number;
export type Desconto = number;
export type Total = number;
export type DataDaAprovacao = string;
export type FormaDaAprovacao = "whatsapp" | "telefone" | "presencial" | "email" | "outro";
export type UsuarioDaAprovacao = string;
export type ObservacaoDaAprovacao = string;
export type MotivoDoCancelamento = string;
export type AgendamentoRelacionado = string;
export type OrcamentoEnviadoPorWhatsAppEm = string;
export type IdentificadorDaMensagemWhatsApp = string;
export type OrcamentoEnviadoPorEMailEm = string;
export type OrdemDeServicoGerada = string;

export interface Quote {
  workshop_id: Oficina;
  number: Numero;
  date?: Data;
  valid_until?: Validade;
  customer_id?: Cliente;
  customer_name_snapshot?: ClienteSnapshot;
  vehicle_id?: Veiculo;
  plate_snapshot?: PlacaSnapshot;
  vehicle_description_snapshot?: VeiculoSnapshot;
  mileage?: Quilometragem;
  customer_report?: RelatoDoCliente;
  diagnosis?: DiagnosticoObservacao;
  notes?: ObservacoesAdicionais;
  forecast?: Previsao;
  images?: FotosAnexadas;
  status?: Status;
  subtotal_parts?: SubtotalPecas;
  subtotal_labor?: SubtotalMaoDeObra;
  socorro?: Socorro;
  discount?: Desconto;
  total?: Total;
  approval_date?: DataDaAprovacao;
  approval_method?: FormaDaAprovacao;
  approval_user?: UsuarioDaAprovacao;
  approval_notes?: ObservacaoDaAprovacao;
  cancel_reason?: MotivoDoCancelamento;
  appointment_id?: AgendamentoRelacionado;
  whatsapp_sent_at?: OrcamentoEnviadoPorWhatsAppEm;
  whatsapp_message_id?: IdentificadorDaMensagemWhatsApp;
  email_sent_at?: OrcamentoEnviadoPorEMailEm;
  work_order_id?: OrdemDeServicoGerada;
}

export type Oficina = string;
export type Orcamento = string;
export type Tipo = "material" | "servico";
export type Descricao = string;
export type Quantidade = number;
export type Unidade = string;
export type ValorUnitario = number;
export type Desconto = number;
export type Total = number;
export type PecaFornecidaPeloCliente = boolean;
export type MaterialOrigem = string;
export type ServicoOrigem = string;
export type Aprovado = boolean;

export interface QuoteItem {
  workshop_id: Oficina;
  quote_id: Orcamento;
  type: Tipo;
  description: Descricao;
  quantity?: Quantidade;
  unit?: Unidade;
  unit_price?: ValorUnitario;
  discount?: Desconto;
  total?: Total;
  customer_provided?: PecaFornecidaPeloCliente;
  material_id?: MaterialOrigem;
  service_id?: ServicoOrigem;
  approved?: Aprovado;
}

export type Oficina = string;
export type Codigo = string;
export type Descricao = string;
export type Categoria = string;
export type ValorPadrao = number;
export type TempoEstimado = string;
export type Observacao = string;
export type Ativo = boolean;

export interface Service {
  workshop_id: Oficina;
  code?: Codigo;
  description: Descricao;
  category?: Categoria;
  default_price?: ValorPadrao;
  estimated_time?: TempoEstimado;
  notes?: Observacao;
  active?: Ativo;
}

export type Oficina = string;
export type Servico = string;
export type CodigoMunicipal = string;
export type ItemDaListaDeServicos = string;
export type NBS = string;
export type AliquotaISS = number;
export type ISSRetido = boolean;
export type MunicipioDeIncidencia = string;
export type NaturezaDaOperacao = string;
export type Exigibilidade = string;
export type ObservacaoFiscal = string;
export type Ativo = boolean;

export interface ServiceFiscalProfile {
  workshop_id: Oficina;
  service_id: Servico;
  codigo_servico_municipal?: CodigoMunicipal;
  item_lista_servico?: ItemDaListaDeServicos;
  nbs?: NBS;
  aliquota_iss?: AliquotaISS;
  iss_retido?: ISSRetido;
  municipio_incidencia_codigo_ibge?: MunicipioDeIncidencia;
  natureza_operacao?: NaturezaDaOperacao;
  exigibilidade?: Exigibilidade;
  configuracoes_retencao?: ConfiguracoesDeRetencao;
  observacao_fiscal?: ObservacaoFiscal;
  active?: Ativo;
}
export interface ConfiguracoesDeRetencao {}

export type Oficina = string;
export type Material = string;
export type Tipo = "PURCHASE_ENTRY" | "FISCAL_ENTRY" | "ADJUSTMENT_IN" | "ADJUSTMENT_OUT";
export type Quantidade = number;
export type CustoUnitario = number;
export type SaldoAnterior = number;
export type SaldoResultante = number;
export type TipoDaOrigem = "FISCAL_DOCUMENT" | "PURCHASE_ORDER" | "MANUAL_ADJUSTMENT";
export type IDDaOrigem = string;
export type ItemDaOrigem = string;
export type DataDaMovimentacao = string;
export type CriadoPor = string;
export type Observacoes = string;

export interface StockMovement {
  workshop_id: Oficina;
  material_id: Material;
  type: Tipo;
  quantity: Quantidade;
  unit_cost?: CustoUnitario;
  previous_stock?: SaldoAnterior;
  resulting_stock?: SaldoResultante;
  source_type: TipoDaOrigem;
  source_id: IDDaOrigem;
  source_item_id: ItemDaOrigem;
  occurred_at: DataDaMovimentacao;
  created_by?: CriadoPor;
  notes?: Observacoes;
}

export type Oficina = string;
export type NomeRazaoSocial = string;
export type TipoDePessoa = "PF" | "PJ" | "EXTERIOR";
export type RazaoSocial = string;
export type NomeFantasia = string;
export type CPFCNPJ = string;
export type InscricaoEstadual = string;
export type InscricaoMunicipal = string;
export type Telefone = string;
export type WhatsApp = string;
export type EMail = string;
export type CEP = string;
export type Endereco = string;
export type Numero = string;
export type Complemento = string;
export type Bairro = string;
export type Cidade = string;
export type Estado = string;
export type CodigoIBGEDoMunicipio = string;
export type Pais = string;
export type CodigoDoPais = string;
export type NomeDoContato = string;
export type Observacoes = string;
export type Ativo = boolean;

export interface Supplier {
  workshop_id: Oficina;
  name: NomeRazaoSocial;
  person_type?: TipoDePessoa;
  razao_social?: RazaoSocial;
  fantasy_name?: NomeFantasia;
  cpf_cnpj?: CPFCNPJ;
  inscricao_estadual?: InscricaoEstadual;
  inscricao_municipal?: InscricaoMunicipal;
  phone?: Telefone;
  whatsapp?: WhatsApp;
  email?: EMail;
  cep?: CEP;
  address?: Endereco;
  number?: Numero;
  complement?: Complemento;
  neighborhood?: Bairro;
  city?: Cidade;
  state?: Estado;
  city_ibge_code?: CodigoIBGEDoMunicipio;
  country?: Pais;
  country_code?: CodigoDoPais;
  contact_name?: NomeDoContato;
  notes?: Observacoes;
  active?: Ativo;
}

export type Oficina = string;
export type Fornecedor = string;
export type Material = string;
export type CodigoDoProdutoNoFornecedor = string;
export type DescricaoNoFornecedor = string;
export type GTINEANNoFornecedor = string;
export type UltimoPreco = number;
export type DataDoUltimoPreco = string;
export type HistoricoDePrecos = {
  date?: string;
  price?: number;
}[];
export type Observacoes = string;
export type Ativo = boolean;

export interface SupplierMaterial {
  workshop_id: Oficina;
  supplier_id: Fornecedor;
  material_id: Material;
  supplier_product_code?: CodigoDoProdutoNoFornecedor;
  supplier_description?: DescricaoNoFornecedor;
  supplier_gtin?: GTINEANNoFornecedor;
  last_price?: UltimoPreco;
  last_price_date?: DataDoUltimoPreco;
  price_history?: HistoricoDePrecos;
  notes?: Observacoes;
  active?: Ativo;
}

/**
 * ID da oficina (tenant) à qual este usuário pertence
 */
export type Oficina = string;

export interface User {
  workshop_id?: Oficina;
}

export type Oficina = string;
export type Tipo = "carro" | "moto" | "caminhonete" | "van" | "caminhao" | "outro";
export type Placa = string;
export type Marca = string;
export type Modelo = string;
export type Versao = string;
export type AnoFabricacao = number;
export type AnoModelo = number;
export type Cor = string;
export type Combustivel = string;
export type Quilometragem = number;
export type Chassi = string;
export type Renavam = string;
export type Observacoes = string;
export type ProprietarioAtual = string;
export type Ativo = boolean;

export interface Vehicle {
  workshop_id: Oficina;
  type?: Tipo;
  plate: Placa;
  brand?: Marca;
  model?: Modelo;
  version?: Versao;
  year_manufacture?: AnoFabricacao;
  year_model?: AnoModelo;
  color?: Cor;
  fuel?: Combustivel;
  mileage?: Quilometragem;
  chassis?: Chassi;
  renavam?: Renavam;
  notes?: Observacoes;
  current_owner_id?: ProprietarioAtual;
  active?: Ativo;
}

export type Oficina = string;
export type Veiculo = string;
export type Cliente = string;
export type NomeDoProprietarioSnapshot = string;
export type Inicio = string;
export type Fim = string;
export type Ativo = boolean;

export interface VehicleOwner {
  workshop_id: Oficina;
  vehicle_id: Veiculo;
  customer_id: Cliente;
  customer_name_snapshot?: NomeDoProprietarioSnapshot;
  start_date?: Inicio;
  end_date?: Fim;
  active?: Ativo;
}

export type Oficina = string;
export type Numero = string;
export type Cliente = string;
export type ClienteSnapshot = string;
export type Veiculo = string;
export type PlacaSnapshot = string;
export type VeiculoSnapshot = string;
export type KmEntrada = number;
export type Entrada = string;
export type PrevisaoEntrega = string;
export type Conclusao = string;
export type Relato = string;
export type Diagnostico = string;
export type MecanicoResponsavel = string;
export type ObservacoesInternas = string;
export type ObservacoesCliente = string;
export type Status = "aberta" | "aguardando_pecas" | "em_execucao" | "finalizada" | "cancelada";
export type MotivoDoCancelamento = string;
export type SubtotalPecas = number;
export type SubtotalMaoDeObra = number;
export type Socorro = number;
export type Desconto = number;
export type Total = number;
export type OrcamentoDeOrigem = string;
export type AgendamentoDeOrigem = string;
export type FotosAnexadas = string[];
export type StatusDePagamento = "nao_pago" | "parcialmente_pago" | "pago" | "isento_cancelado";
export type ValorPago = number;
export type ClienteNotificado = boolean;
export type NotificadoEm = string;
export type CanalDaNotificacao = "whatsapp" | "telefone" | "email" | "presencial" | "outro";
export type NotificadoPor = string;

export interface WorkOrder {
  workshop_id: Oficina;
  number: Numero;
  customer_id?: Cliente;
  customer_name_snapshot?: ClienteSnapshot;
  vehicle_id?: Veiculo;
  plate_snapshot?: PlacaSnapshot;
  vehicle_description_snapshot?: VeiculoSnapshot;
  mileage_in?: KmEntrada;
  entry_date?: Entrada;
  expected_delivery?: PrevisaoEntrega;
  completion_date?: Conclusao;
  customer_report?: Relato;
  diagnosis?: Diagnostico;
  mechanic_id?: MecanicoResponsavel;
  internal_notes?: ObservacoesInternas;
  customer_notes?: ObservacoesCliente;
  status?: Status;
  cancel_reason?: MotivoDoCancelamento;
  subtotal_parts?: SubtotalPecas;
  subtotal_labor?: SubtotalMaoDeObra;
  socorro?: Socorro;
  discount?: Desconto;
  total?: Total;
  quote_id?: OrcamentoDeOrigem;
  appointment_id?: AgendamentoDeOrigem;
  images?: FotosAnexadas;
  payment_status?: StatusDePagamento;
  paid_amount?: ValorPago;
  customer_notified?: ClienteNotificado;
  notified_at?: NotificadoEm;
  notified_channel?: CanalDaNotificacao;
  notified_by?: NotificadoPor;
}

export type Oficina = string;
export type OS = string;
export type Tipo = "material" | "servico";
export type Descricao = string;
export type Quantidade = number;
export type Unidade = string;
export type TratamentoFiscal = "automatico" | "incluir" | "excluir";
export type ValorUnitario = number;
export type Desconto = number;
export type Total = number;
export type PecaFornecidaPeloCliente = boolean;
export type MaterialOrigem = string;
export type ServicoOrigem = string;
export type AdicionadoAposAprovacao = boolean;
export type StatusDeAprovacao = "aprovado" | "aguardando" | "recusado";

export interface WorkOrderItem {
  workshop_id: Oficina;
  work_order_id: OS;
  type: Tipo;
  description: Descricao;
  quantity?: Quantidade;
  unit?: Unidade;
  fiscal_treatment?: TratamentoFiscal;
  unit_price?: ValorUnitario;
  discount?: Desconto;
  total?: Total;
  customer_provided?: PecaFornecidaPeloCliente;
  material_id?: MaterialOrigem;
  service_id?: ServicoOrigem;
  added_after_approval?: AdicionadoAposAprovacao;
  approval_status?: StatusDeAprovacao;
}

export interface WorkshopAccess {
  email: string;
  workshop_id: string;
  role: "admin" | "user";
}

export type NomeDaOficina = string;
export type RazaoSocial = string;
export type CNPJ = string;
export type Telefone = string;
export type WhatsApp = string;
export type EMail = string;
export type EnderecoLegado = string;
export type CEP = string;
export type Logradouro = string;
export type Numero = string;
export type Complemento = string;
export type Bairro = string;
export type Cidade = string;
export type UF = string;
export type CodigoIBGE = string;
export type Pais = string;
export type CodigoDoPais = string;
export type Logo = string;
export type TextoPadraoOrcamento = string;
export type ValidadePadraoDias = number;
export type ObservacaoPadraoOS = string;
export type CapacidadePadrao = number;
export type EMailDoProprietario = string;
export type AgendaAbertaNaSegunda = boolean;
export type AgendaAbertaNaTerca = boolean;
export type AgendaAbertaNaQuarta = boolean;
export type AgendaAbertaNaQuinta = boolean;
export type AgendaAbertaNaSexta = boolean;
export type AgendaAbertaNoSabado = boolean;
export type AgendaAbertaNoDomingo = boolean;
export type CapacidadeSegunda = number;
export type CapacidadeTerca = number;
export type CapacidadeQuarta = number;
export type CapacidadeQuinta = number;
export type CapacidadeSexta = number;
export type CapacidadeSabado = number;
export type CapacidadeDomingo = number;
export type OficinaDeDemonstracao = boolean;
export type OficinaAtiva = boolean;
export type EMailDemo = string;
export type SenhaDemo = string;
export type Plano = "free" | "normal";
export type ValorMensalR$ = number;
export type ModuloFiscalHabilitado = boolean;
export type InicioDoPeriodoTrial = string;
export type CategoriasDeDespesa = string[];

export interface WorkshopSetting {
  name?: NomeDaOficina;
  razao_social?: RazaoSocial;
  cnpj?: CNPJ;
  phone?: Telefone;
  whatsapp?: WhatsApp;
  email?: EMail;
  address?: EnderecoLegado;
  cep?: CEP;
  logradouro?: Logradouro;
  numero?: Numero;
  complemento?: Complemento;
  bairro?: Bairro;
  cidade?: Cidade;
  uf?: UF;
  codigo_ibge?: CodigoIBGE;
  pais?: Pais;
  codigo_pais?: CodigoDoPais;
  logo_url?: Logo;
  default_quote_text?: TextoPadraoOrcamento;
  default_validity_days?: ValidadePadraoDias;
  default_os_note?: ObservacaoPadraoOS;
  default_capacity?: CapacidadePadrao;
  owner_email?: EMailDoProprietario;
  schedule_monday?: AgendaAbertaNaSegunda;
  schedule_tuesday?: AgendaAbertaNaTerca;
  schedule_wednesday?: AgendaAbertaNaQuarta;
  schedule_thursday?: AgendaAbertaNaQuinta;
  schedule_friday?: AgendaAbertaNaSexta;
  schedule_saturday?: AgendaAbertaNoSabado;
  schedule_sunday?: AgendaAbertaNoDomingo;
  capacity_monday?: CapacidadeSegunda;
  capacity_tuesday?: CapacidadeTerca;
  capacity_wednesday?: CapacidadeQuarta;
  capacity_thursday?: CapacidadeQuinta;
  capacity_friday?: CapacidadeSexta;
  capacity_saturday?: CapacidadeSabado;
  capacity_sunday?: CapacidadeDomingo;
  is_demo?: OficinaDeDemonstracao;
  is_active?: OficinaAtiva;
  demo_email?: EMailDemo;
  demo_password?: SenhaDemo;
  plan?: Plano;
  plan_value?: ValorMensalR$;
  fiscal_module_enabled?: ModuloFiscalHabilitado;
  trial_started_at?: InicioDoPeriodoTrial;
  expense_categories?: CategoriasDeDespesa;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "Appointment": Appointment;
    "AppointmentHistory": AppointmentHistory;
    "Customer": Customer;
    "EvolutionGoConfig": EvolutionGoConfig;
    "Expense": Expense;
    "FinancialTransaction": FinancialTransaction;
    "FiscalCredential": FiscalCredential;
    "FiscalDocument": FiscalDocument;
    "FiscalDocumentEvent": FiscalDocumentEvent;
    "FiscalDocumentItem": FiscalDocumentItem;
    "FiscalOperationLock": FiscalOperationLock;
    "FiscalSetting": FiscalSetting;
    "Material": Material;
    "MaterialCategory": MaterialCategory;
    "MaterialFiscalProfile": MaterialFiscalProfile;
    "Payment": Payment;
    "PurchaseOrder": PurchaseOrder;
    "PurchaseOrderItem": PurchaseOrderItem;
    "PurchaseRequest": PurchaseRequest;
    "PurchaseRequestItem": PurchaseRequestItem;
    "Quote": Quote;
    "QuoteItem": QuoteItem;
    "Service": Service;
    "ServiceFiscalProfile": ServiceFiscalProfile;
    "StockMovement": StockMovement;
    "Supplier": Supplier;
    "SupplierMaterial": SupplierMaterial;
    "User": User;
    "Vehicle": Vehicle;
    "VehicleOwner": VehicleOwner;
    "WorkOrder": WorkOrder;
    "WorkOrderItem": WorkOrderItem;
    "WorkshopAccess": WorkshopAccess;
    "WorkshopSetting": WorkshopSetting;
  }

  interface FunctionNameRegistry {
    "getDemoAccess": true;
    "manageFiscal": true;
    "manageAccountingCenter": true;
    "manageWorkshops": true;
    "manageEvolutionGoConfig": true;
    "manageInboundFiscal": true;
    "sendWhatsAppDocument": true;
  }
}
